'use strict';

const DEFAULT_COMMAND = `--help`;
const USER_ARGV_INDEX = 2;
const EXIT_CODES = {
  SUCCESS: 0
};

const JSON_LIMIT = 100000;

const HTTP_CODES = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  UNAUTHORIZED: 401,
  INTERNAL_SERVER_ERROR: 500
};

const DEFAULT_API_PORT = 3000;

const HTTP_METHODS = {
  GET: `GET`,
  POST: `POST`,
  PUT: `PUT`,
  DELETE: `DELETE`
};

module.exports = {
  DEFAULT_COMMAND,
  USER_ARGV_INDEX,
  EXIT_CODES,
  HTTP_CODES,
  JSON_LIMIT,
  DEFAULT_API_PORT,
  HTTP_METHODS
};
